# Generated by Django 3.1.1 on 2020-09-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200924_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='5f6c6b746e4a5d83154f7459', max_length=24, primary_key=True, serialize=False),
        ),
    ]
