#%RAML 1.0
title: DeepLibrary API
baseUri: http://api.deeplibrary.io/{version}
version: v1
protocols: [HTTP, HTTPS]

traits:
  secured:
    usage: Apply this to any method that needs to be secured
    description: Most requests require authentication.
    headers:
      Authorization:
        displayName: Authorization
        description: "The access token provided by the authentication application"
        type: string
        required: true
        example: "Token 9af36176dddf7673d5e7de6c00860d580bbf0670"

resourceTypes:
  collection:
    is: [secured]
    usage: This resourceType should be used for any collection of items
    description: Collection of available <<resourcePathName>>
    get:
      description: Get a list of <<resourcePathName>> based on the title.
      responses:
        200:
          body:
            application/json:
    post:
      description: Add a new <<resourcePathName | !singularize>>
      body:
        application/json:
          type: <<resourcePathName | !singularize | !uppercamelcase>>
      responses:
        200:
          body:
            application/json:
              type: Message
              example:
                message: "The <<resourcePathName | !singularize>> has been properly entered"
  collection-item:
    is: [secured]
    usage: This resourceType should be used for any item
    description: A <<resourcePathName | !singularize | !uppercamelcase>> entity
    get:
      description: Get details of <<resourcePathName | !singularize>>
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName | !singularize | !uppercamelcase>>
    put:
      description: Update details of <<resourcePathName | !singularize>>
      body:
        application/json:
          type: <<resourcePathName | !singularize | !uppercamelcase>>
    delete:
      description: Delete a <<resourcePathName | !singularize>>
      responses:
        200:
          body:
            application/json:
              type: Message
              example:
                message: "The <<resourcePathName | !singularize>> has succefully deleted"

  content:
    is: [secured]
    description: The content of the <<resourcePathName | !singularize>>
    put:
      description: Update the content of the <<resourcePathName | !singularize>>
      body:
        application/pdf:
      responses:
        200:
          body:
            application/json:
              type: Message
              example:
                message: "Content updated successfully"
    delete:
      description: Delete the content of <<resourcePathName | !singularize>>
      responses:
        200:
          body:
            application/json:
              type: Message
              example:
                message: "Content deleted successfully"
    post:
      description: Insert content for <<resourcePathName | !singularize>>
      body:
        application/pdf:
      responses:
        200:
          body:
            application/json:
              type: Message
              example:
                message: "Content Inserted successfully"
  page:
    is: [secured]
    description: The Page to be streamed
    get:
      description: Stream a page
      responses:
        200:
          body:
            application/pdf:

types:
  Message:
    properties:
      message:
        type: string
        required: true
  Page:
    properties:
      pageNumber:
        type: integer
        required: true
  DigitaldDocument:
    properties:
      numberOfPages:
        type: integer
      title:
        type: string
      year:
        type: integer
      country:
        type: string
      city:
        type: string
      authors:
        type: string[]
  Book:
    type: DigitaldDocument
    properties:
      isbn:
        type: string
      publisher:
        type: string
      preface:
        type: string
      volume:
        type: integer
      edition:
          type: integer
      language:
        type: string

/{collection-name}:
  type: collection
  get:
  post:
  /{resource-id}:
    type: collection-item
    get:
    put:
    delete:
    /content:
      type: content
      is: [secured]
      post:
      delete:
      put:
    /{page-number}:
      type: page
      is: [secured]
      get:
